"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:1,2,3,5,8,13,21,34,55,89...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

a=1
b=2
x=1
tot=0
while(a<=4000000 or b<=4000000):
	x+=1
	if(x%2==0):
		if(a%2==0):
			tot=tot+a
		print(a)
		a=a+b
	else:
		if(b%2==0):
			tot=tot+b
		print(b)
		b=b+a
print(tot)
