"""Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?"""

pents=[]
for x in range(1,2400):
	pents.append(x*((3*x)-1)/2)
#print(pents)
for a in pents:
	for b in pents:
		if((a+b) in pents and ((a-b) in pents or (b-a) in pents)):
			print(a-b)
			print(b-a)
